In [1]:
import numpy as np

1. Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей
 

In [2]:
A = np.array([[-1, -6], [2, 6]])

print(f'A:\n{A}\n')

A:
[[-1 -6]
 [ 2  6]]



v1 = (-2, 1)
v2 = (3/2, -1)

In [3]:
v1 = np.array([-2, 1])
v2 = np.array([3/2, -1])

n1 = np.linalg.norm(v1)
n2 = np.linalg.norm(v2)

print(f'A:\n{A}\n')
print(f'Собственные значения:\n{np.array([2, 3])}\n')
print(f'Собственные векторы:\n{v1}, {v2}\n')
print(f'Нормированные собственные векторы:\n{v1/n1}, {v2/n2}\n')

A:
[[-1 -6]
 [ 2  6]]

Собственные значения:
[2 3]

Собственные векторы:
[-2  1], [ 1.5 -1. ]

Нормированные собственные векторы:
[-0.89442719  0.4472136 ], [ 0.83205029 -0.5547002 ]



In [4]:
w, v = np.linalg.eig(A)

print(f'A:\n{A}\n')
print(f'Собственные значения:\n{w}\n')
print(f'Собственные векторы:\n{v[:, 0]}, {v[:, 1]}\n')

A:
[[-1 -6]
 [ 2  6]]

Собственные значения:
[2. 3.]

Собственные векторы:
[-0.89442719  0.4472136 ], [ 0.83205029 -0.5547002 ]



2. Дан оператор поворота на 180 градусов, задаваемый матрицей
 
Показать, что любой вектор является для него собственным.

In [5]:
A = np.array([[-1, 0], [0, -1]])

print(f'A:\n{A}\n')

A:
[[-1  0]
 [ 0 -1]]



In [6]:
w, v = np.linalg.eig(A)

print(f'A:\n{A}\n')
print(f'Собственные значения:\n{w}\n')
print(f'Собственные векторы:\n{v[:, 0]}, {v[:, 1]}\n')

A:
[[-1  0]
 [ 0 -1]]

Собственные значения:
[-1. -1.]

Собственные векторы:
[1. 0.], [0. 1.]



Собственным вектором линейного оператора A (матрицы A) называется ненулевой вектор x такой, что Ax = λx.
Для единичной матрицы E любой вектор x является собственным, с собственным числом, равным 1, так как Ex = x.
Так как матрица A диагональная, тогда собственные значения: λ 1=-1, λ 2=-1
А=-1Е
-1Ех=λ х
-1х=λ х
λ =-1

Таким образом, любой ненулевой вектор х является собственным для линейного оператора А=-1Е

In [7]:
x = np.array([np.random.randint(1, 999), np.random.randint(1, 999)])

trials = []

n = 100000

for _ in range(n):
    trial = np.array_equal(np.dot(A, x), -1 * x)
    trials.append(trial)
    
print(np.sum(trials) / n)

1.0


3. Пусть линейный оператор задан матрицей
A=(1/−1;1/3).

Установить, является ли вектор x=(1,1) собственным вектором этого линейного оператора.
(1/−1;1/3) (1/1)=λ (1/1)

 {1+1=1*λ⇒ {λ=2
 {-1+3=1*λ⇒{λ=2
 Ответ: вектор x=(1,1) является собственным вектором линейного оператора A, а его собственное значения составляет λ=2.

4. Пусть линейный оператор задан матрицей

A=(0/3/0; 3/0/0; 0/0/3) 

Установить, является ли вектор x=(3,−3,−4) собственным вектором этого линейного оператора.
(0/3/0; 3/0/0; 0/0/3) (3/-3/-4)= λ(3/-3/-4)
⇒ {3λ=-9              {λ=-3
   {-3λ=-9         ⇒   {λ=-3 
   {-4λ=-12            {λ=3
   
Ответ: вектор x=(3,−3,−4) не является собственным вектором линейного оператора A.