In [1]:
import numpy as np

1.Решить систему уравнений методом Гаусса:
{x1+x2−x3−2x4=0,2x1+x2−x3+x4=−2,x1+x2−3x3+x4=4.
Запишем систему в виде расширенной матрицы.
(11−1−221−1111−31|0−24).
Умножим 1 строку на -2 и сложим со 2 строкой.
Умножим 1 строку на -1 и сложим с 3 строкой.
(11−1−20−11500−23|0−24).
Разделим каждую строку матрицы на соответствующий ведущий элемент: 1 строку на 1, 2 строку на -2, 3 строку на -2.
(11−1−201−1−5002−3/2|02−2).
Выразим x1,x2,x3 относительно остальных переменных.
x1=−x2+x3+2x4
x2=2+x3+5x4
x3=−2+3/2x4
Решение:
x1=−2−3x4
x2=13/2x4
x3=−2+3/2x4
x4 - произвольное действительное число
Частное решение:
x1=−2
x2=0
x3=−2
x4=0


2. Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:
а) ⎧3x1−x2+x3=4,2x1−5x2−3x3=−17,x1+x2−x3=0;
б) ⎧2x1−4x2+6x3=1,x1−2x2+3x3=−2,3x1−6x2+9x3=5;
в) {x1+2x2+5x3=4,3x1+x2−8x3=−2.


Теорема
Необходимым и достаточным условием совместности системы из m уравнений с n неизвестными является равенство между собой рангов матрицы коэффициентов A и расширенной матрицы A~
rankA=rankA~.
Причем:
1) если rankA=rankA~=n, где n — число неизвестных, то система определена, т. е. имеет единственное решение;
2) если rankA=rankA~<n, то система имеет бесконечное количество решений;
3) если rankA<rankA~, то система несовместна.


In [2]:
A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
b = np.array([4, -17, 0])
A_ext = np.column_stack([A, b])

rank_A = np.linalg.matrix_rank(A)
rank_A_ext = np.linalg.matrix_rank(A_ext)
n = len(A[0])

print(f'A:\n{A}\n')
print(f'A_ext:\n{A_ext}\n')

print(f'rank(A): {rank_A}\n')
print(f'rank(A_ext): {rank_A_ext}\n')
print(f'# of vars: {n}\n')

if rank_A == rank_A_ext == n:
    print(f'Система имеет единственное решение.')
elif rank_A == rank_A_ext < n:
    print(f'Система имеет бесконечное кол-во решений.')
elif rank_A < rank_A_ext:
    print(f'Система несовместна.')

A:
[[ 3 -1  1]
 [ 2 -5 -3]
 [ 1  1 -1]]

A_ext:
[[  3  -1   1   4]
 [  2  -5  -3 -17]
 [  1   1  -1   0]]

rank(A): 3

rank(A_ext): 3

# of vars: 3

Система имеет единственное решение.


In [3]:
A = np.array([[3, -4, 6], [1, -2, 3], [3, -6, 9]])
b = np.array([1, -2, 5])
A_ext = np.column_stack([A, b])

rank_A = np.linalg.matrix_rank(A)
rank_A_ext = np.linalg.matrix_rank(A_ext)
n = len(A[0])

print(f'A:\n{A}\n')
print(f'A_ext:\n{A_ext}\n')

print(f'rank(A): {rank_A}\n')
print(f'rank(A_ext): {rank_A_ext}\n')
print(f'# of vars: {n}\n')

if rank_A == rank_A_ext == n:
    print(f'Система имеет единственное решение.')
elif rank_A == rank_A_ext < n:
    print(f'Система имеет бесконечное кол-во решений.')
elif rank_A < rank_A_ext:
    print(f'Система несовместна.')

A:
[[ 3 -4  6]
 [ 1 -2  3]
 [ 3 -6  9]]

A_ext:
[[ 3 -4  6  1]
 [ 1 -2  3 -2]
 [ 3 -6  9  5]]

rank(A): 2

rank(A_ext): 3

# of vars: 3

Система несовместна.


In [4]:
A = np.array([[1, 2, 5], [3, 1, -8]])
b = np.array([4, -2])
A_ext = np.column_stack([A, b])

rank_A = np.linalg.matrix_rank(A)
rank_A_ext = np.linalg.matrix_rank(A_ext)
n = len(A[0])

print(f'A:\n{A}\n')
print(f'A_ext:\n{A_ext}\n')

print(f'rank(A): {rank_A}\n')
print(f'rank(A_ext): {rank_A_ext}\n')
print(f'# of vars: {n}\n')

if rank_A == rank_A_ext == n:
    print(f'Система имеет единственное решение.')
elif rank_A == rank_A_ext < n:
    print(f'Система имеет бесконечное кол-во решений.')
elif rank_A < rank_A_ext:
    print(f'Система несовместна.')

A:
[[ 1  2  5]
 [ 3  1 -8]]

A_ext:
[[ 1  2  5  4]
 [ 3  1 -8 -2]]

rank(A): 2

rank(A_ext): 2

# of vars: 3

Система имеет бесконечное кол-во решений.


3. Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

In [5]:
A = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
b = np.array([3, 2, 4, 1])
A_ext = np.column_stack([A, b])

rank_A = np.linalg.matrix_rank(A)
rank_A_ext = np.linalg.matrix_rank(A_ext)
n = len(A[0])

print(f'A:\n{A}\n')
print(f'A_ext:\n{A_ext}\n')

print(f'rank(A): {rank_A}\n')
print(f'rank(A_ext): {rank_A_ext}\n')
print(f'# of vars: {n}\n')

if rank_A == rank_A_ext == n:
    print(f'Система имеет единственное решение.')
elif rank_A == rank_A_ext < n:
    print(f'Система имеет бесконечное кол-во решений.')
elif rank_A < rank_A_ext:
    print(f'Система несовместна.')

A:
[[ 1  3 -2  4]
 [ 0  5  0  1]
 [ 0  0  3  0]
 [ 0  0  0  2]]

A_ext:
[[ 1  3 -2  4  3]
 [ 0  5  0  1  2]
 [ 0  0  3  0  4]
 [ 0  0  0  2  1]]

rank(A): 4

rank(A_ext): 4

# of vars: 4

Система имеет единственное решение.


4. Дана система линейных уравнений, заданная расширенной матрицей
A~=(123456789|abc).
Найти соотношение между параметрами a, b и c, при которых система является несовместной.
Запишем систему в виде расширенной матрицы.
(123 456789|abc).
1 строку умножим на 2 и вычтем и 2 строки.
1 строку умножим на 3 и вычтем и 3 строки.
(123 210420|ab−2ac−3a).
2 строку умножим на 2 и вычтем из 3 строки.
(123 210000|ab−2ac−3a−2b).
Если c - 3a - 2b != 0, то система несовместна.


In [6]:
import numpy as np
import scipy.linalg

1. Решить систему уравнений методом Крамера:
а) {x1−2x2=1; 3x1−4x2=7
б) ⎩2x1−x2+5x3=10; x1+x2−3x3=−2; 2x1+4x2+x3=1


In [7]:
# а)

A = np.array([[1, -2], [3, -4]])
b = np.array([1, 7])

det_A = np.linalg.det(A)

print(f'A:\n{A}\n')
print(f'b:\n{b}\n')

print(f'det(A): {det_A}\n')

if det_A != 0:
    print(f'Определитель матрицы квадратной системы не равен 0, система совместна и имеет единственное решение.\n')

A1 = np.column_stack([b, A[:, 1]])
det_A1 = np.linalg.det(A1)

print(f'A1:\n{A1}\n')
print(f'det(A1): {det_A1}\n')

A2 = np.column_stack([A[:, 0], b])
det_A2 = np.linalg.det(A2)

print(f'A2:\n{A2}\n')
print(f'det(A2): {det_A2}\n')

print(f'x1 = {det_A1 / det_A}')
print(f'x2 = {det_A2 / det_A}')

A:
[[ 1 -2]
 [ 3 -4]]

b:
[1 7]

det(A): 2.0000000000000004

Определитель матрицы квадратной системы не равен 0, система совместна и имеет единственное решение.

A1:
[[ 1 -2]
 [ 7 -4]]

det(A1): 9.999999999999998

A2:
[[1 1]
 [3 7]]

det(A2): 4.0

x1 = 4.999999999999998
x2 = 1.9999999999999996


In [8]:
# б)

A = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b = np.array([10, -2, 1])

det_A = np.linalg.det(A)

print(f'A:\n{A}\n')
print(f'b:\n{b}\n')

print(f'det(A): {det_A}\n')

if det_A != 0:
    print(f'Определитель матрицы квадратной системы не равен 0, система совместна и имеет единственное решение.\n')

A1 = np.column_stack([b, A[:, 1:]])
det_A1 = np.linalg.det(A1)

print(f'A1:\n{A1}\n')
print(f'det(A1): {det_A1}\n')

A2 = np.column_stack([A[:, 0], b, A[:, 2]])
det_A2 = np.linalg.det(A2)

print(f'A2:\n{A2}\n')
print(f'det(A2): {det_A2}\n')

A3 = np.column_stack([A[:, 0:2], b])
det_A3 = np.linalg.det(A3)

print(f'A3:\n{A3}\n')
print(f'det(A3): {det_A3}\n')

print(f'x1 = {det_A1 / det_A}')
print(f'x2 = {det_A2 / det_A}')
print(f'x3 = {det_A3 / det_A}')

A:
[[ 2 -1  5]
 [ 1  1 -3]
 [ 2  4  1]]

b:
[10 -2  1]

det(A): 42.99999999999998

Определитель матрицы квадратной системы не равен 0, система совместна и имеет единственное решение.

A1:
[[10 -1  5]
 [-2  1 -3]
 [ 1  4  1]]

det(A1): 86.00000000000004

A2:
[[ 2 10  5]
 [ 1 -2 -3]
 [ 2  1  1]]

det(A2): -43.000000000000014

A3:
[[ 2 -1 10]
 [ 1  1 -2]
 [ 2  4  1]]

det(A3): 42.99999999999998

x1 = 2.0000000000000018
x2 = -1.0000000000000009
x3 = 1.0


2. Найти L-матрицу LU-разложения для матрицы коэффициентов:

In [9]:
A = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
U = np.array([[1, 2, 4], [0, 5, 4], [0, 0, 2]])
L = np.array([[1, 0, 0], [2, 1, 0], [3, 4, 1]])

LU = np.dot(L, U)

print(f'A:\n{A}\n')
print(f'L:\n{L}\n')
print(f'U:\n{U}\n')
print(f'LU:\n{LU}\n')

A:
[[ 1  2  4]
 [ 2  9 12]
 [ 3 26 30]]

L:
[[1 0 0]
 [2 1 0]
 [3 4 1]]

U:
[[1 2 4]
 [0 5 4]
 [0 0 2]]

LU:
[[ 1  2  4]
 [ 2  9 12]
 [ 3 26 30]]



In [10]:
A = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])
U = np.array([[1, 1, 2, 4], [0, 3, 4, 1], [0, 0, 3, 1], [0, 0, 0, 4]])
L = np.array([[1, 0, 0, 0], [2, 1, 0, 0], [3, 5, 1, 0], [4, 6, 7, 1]])

LU = np.dot(L, U)

print(f'A:\n{A}\n')
print(f'L:\n{L}\n')
print(f'U:\n{U}\n')
print(f'LU:\n{LU}\n')

A:
[[ 1  1  2  4]
 [ 2  5  8  9]
 [ 3 18 29 18]
 [ 4 22 53 33]]

L:
[[1 0 0 0]
 [2 1 0 0]
 [3 5 1 0]
 [4 6 7 1]]

U:
[[1 1 2 4]
 [0 3 4 1]
 [0 0 3 1]
 [0 0 0 4]]

LU:
[[ 1  1  2  4]
 [ 2  5  8  9]
 [ 3 18 29 18]
 [ 4 22 53 33]]



3. Решить систему линейных уравнений методом LU-разложения
⎩2x1+x2+3x3=111x1+7x2+5x3=−69x1+8x2+4x3=−5


In [11]:
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
b = np.array([1, -6, -5])

lu, piv = scipy.linalg.lu_factor(A)
x = scipy.linalg.lu_solve((lu, piv), b)

print(f'A:\n{A}\n')
print(f'b:\n{b}\n')
print(f'x:\n{x}\n')
print(f'Ax:\n{A @ x}\n')
print(f'Ax - b:\n{A @ x - b}\n')

A:
[[ 2  1  3]
 [11  7  5]
 [ 9  8  4]]

b:
[ 1 -6 -5]

x:
[-1.00000000e+00  2.44249065e-16  1.00000000e+00]

Ax:
[ 1. -6. -5.]

Ax - b:
[0. 0. 0.]



4. Решить систему линейных уравнений методом Холецкого
⎩81x1−45x2+45x3=531−45x1+50x2−15x3=−46045x1−15x2+38x3=193


In [12]:
A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
b = np.array([531, -460, 193])

K = scipy.linalg.cho_factor(A)
x = scipy.linalg.cho_solve(K, b)

print(f'A:\n{A}\n')
print(f'b:\n{b}\n')
print(f'x:\n{x}\n')
print(f'Ax:\n{A @ x}\n')
print(f'Ax - b:\n{A @ x - b}\n')

A:
[[ 81 -45  45]
 [-45  50 -15]
 [ 45 -15  38]]

b:
[ 531 -460  193]

x:
[ 6. -5. -4.]

Ax:
[ 531. -460.  193.]

Ax - b:
[0. 0. 0.]

