1. Установить, какие произведения матриц AB и BA определены, и найти размерности полученных матриц:
а) A — матрица 4×2, B — матрица 4×2;
б) A — матрица 2×5, B — матрица 5×3;
в) A — матрица 8×3, B — матрица 3×8;
г) A — квадратная матрица 4×4, B — квадратная матрица 4×4.


Вариант a:
A∗B = 4×2 и 4×2
B∗A = 4×2 и 4×2
Произведения не определены


Вариант б:
A∗B = 2×5 и 5×3, произведение определено, размерность полученной матрицы 2×3
B∗A = 5×3 и 2×5, произведение не определено


Вариант в:
A∗B = 8×3 и 3×8, произведение определено, размерность полученной матрицы 8×8
B∗A = 3×8 и 8×3, произведение определено, размерность полученной матрицы 3*3


Вариант г:
A∗B, B∗A - оба произведения определены, размерность полученной матрицы 4*4


In [1]:
import numpy as np

In [2]:
def generate_matrix(n, m, min_value=0, max_value=9):
    try:
        return np.random.randint(min_value, max_value+1, (n, m))
    except Exception as e:
        return e

def check(A, B):
    try:
        if len(A[0]) == len(B):
            return True
        else:
            return False
    except Exception as e:
        print(f'Exception: {e}')
        return False
    

In [3]:
# а)

A = generate_matrix(4, 2)
B = generate_matrix(4, 2)

print(f'A:\n{A}\n')
print(f'B:\n{B}\n')

if check(A, B):
    print(f'A x B:\n{np.dot(A, B)}\n')
else:
    print('Произведение матриц A x B не определено.\n')
    
if check(B, A):
    print(f'B x A:\n{np.dot(B, A)}\n')
else:
    print('Произведение матриц A x B не определено.\n')

A:
[[6 6]
 [2 5]
 [3 4]
 [0 3]]

B:
[[0 6]
 [3 6]
 [6 6]
 [0 1]]

Произведение матриц A x B не определено.

Произведение матриц A x B не определено.



In [4]:
# б)

A = generate_matrix(2, 5)
B = generate_matrix(5, 3)

print(f'A:\n{A}\n')
print(f'B:\n{B}\n')

if check(A, B):
    print(f'A x B:\n{np.dot(A, B)}\n')
else:
    print('Произведение матриц A x B не определено.\n')
    
if check(B, A):
    print(f'B x A:\n{np.dot(B, A)}\n')
else:
    print('Произведение матриц A x B не определено.\n')
    

A:
[[8 3 9 9 3]
 [2 8 7 7 0]]

B:
[[5 4 8]
 [7 6 3]
 [1 4 1]
 [3 1 4]
 [0 9 2]]

A x B:
[[ 97 122 124]
 [ 94  91  75]]

Произведение матриц A x B не определено.



In [5]:
# в)

A = generate_matrix(8, 3)
B = generate_matrix(3, 8)

print(f'A:\n{A}\n')
print(f'B:\n{B}\n')

if check(A, B):
    print(f'A x B:\n{np.dot(A, B)}\n')
else:
    print('Произведение матриц A x B не определено.\n')
    
if check(B, A):
    print(f'B x A:\n{np.dot(B, A)}\n')
else:
    print('Произведение матриц A x B не определено.\n')
    

A:
[[0 9 7]
 [2 7 0]
 [6 1 7]
 [9 2 1]
 [7 4 3]
 [6 7 0]
 [6 4 6]
 [4 8 6]]

B:
[[8 9 0 9 4 1 6 7]
 [0 7 7 9 2 1 5 5]
 [8 9 0 2 0 0 2 3]]

A x B:
[[ 56 126  63  95  18   9  59  66]
 [ 16  67  49  81  22   9  47  49]
 [104 124   7  77  26   7  55  68]
 [ 80 104  14 101  40  11  66  76]
 [ 80 118  28 105  36  11  68  78]
 [ 48 103  49 117  38  13  71  77]
 [ 96 136  28 102  32  10  68  80]
 [ 80 146  56 120  32  12  76  86]]

B x A:
[[197 256 155]
 [207 149 124]
 [ 60 171  88]]



In [6]:
# г)

A = generate_matrix(4, 4)
B = generate_matrix(4, 4)

print(f'A:\n{A}\n')
print(f'B:\n{B}\n')

if check(A, B):
    print(f'A x B:\n{np.dot(A, B)}\n')
else:
    print('Произведение матриц A x B не определено.\n')
    
if check(B, A):
    print(f'B x A:\n{np.dot(B, A)}\n')
else:
    print('Произведение матриц A x B не определено.\n')
    

A:
[[2 2 4 0]
 [9 3 8 9]
 [0 3 0 2]
 [8 3 4 5]]

B:
[[9 8 0 5]
 [9 7 9 0]
 [0 4 5 9]
 [9 9 5 6]]

A x B:
[[ 36  46  38  46]
 [189 206 112 171]
 [ 45  39  37  12]
 [144 146  72 106]]

B x A:
[[130  57 120  97]
 [ 81  66  92  81]
 [108  54  68  91]
 [147  78 132 121]]



2. Найти сумму и произведение матриц А=(1/3;-2/0)  и В (4/0;-1/5)

In [7]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'A:\n{A}\n')
print(f'B:\n{B}\n')

print(f'A + B:\n{A + B}\n')
print(f'A x B:\n{np.dot(A, B)}\n')
print(f'B x A:\n{np.dot(B, A)}\n')

A:
[[ 1 -2]
 [ 3  0]]

B:
[[ 4 -1]
 [ 0  5]]

A + B:
[[ 5 -3]
 [ 3  5]]

A x B:
[[  4 -11]
 [ 12  -3]]

B x A:
[[ 1 -8]
 [15  0]]



3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию 3А-2В+4С для матриц А=(1/3;7/-6), В=(0/2;5/-1), С=(2/1;-4/1)

In [8]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

print(f'A:\n{A}\n')
print(f'B:\n{B}\n')
print(f'C:\n{C}\n')

print(f'3A - 2B + 4C:\n{3 * A - 2 * B + 4 * C}\n')

A:
[[ 1  7]
 [ 3 -6]]

B:
[[ 0  5]
 [ 2 -1]]

C:
[[ 2 -4]
 [ 1  1]]

3A - 2B + 4C:
[[ 11  -5]
 [  9 -12]]



4. Дана матрица А=(4/5/2;1/-2/3). Вычислить АА*Т и А*Т А

In [9]:
A = np.array([[4, 1], [5, -2], [2, 3]])

print(f'A:\n{A}\n')
print(f'A.T:\n{A.T}\n')

print(f'A x A.T:\n{np.dot(A, A.T)}\n')
print(f'A.T x A:\n{np.dot(A.T, A)}\n')

A:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]

A.T:
[[ 4  5  2]
 [ 1 -2  3]]

A x A.T:
[[17 18 11]
 [18 29  4]
 [11  4 13]]

A.T x A:
[[45  0]
 [ 0 14]]



In [10]:
import numpy as np
import math
import copy

In [11]:
def matrix_determinant_2x2_3x3(A):
    try:
        if len(A) == len(A[0]):
            if len(A) == 2:
                det = A[0][0] * A[1][1] - A[0][1] * A[1][0]
                return det
            elif len(A) == 3:
                det = (
                    A[0][0] * A[1][1] * A[2][2] +
                    A[0][1] * A[1][2] * A[2][0] +
                    A[0][2] * A[1][0] * A[2][1] -
                    A[0][2] * A[1][1] * A[2][0] -
                    A[0][1] * A[1][0] * A[2][2] -
                    A[0][0] * A[1][2] * A[2][1]
                )
                return det
            else:
                return 'Only 2x2 or 3x3 matricies'
        else:
            return 'Determinant is not defined'
    except Exception as e:
        return e
    

1. Вычислить определитель: а) |sinx -cosx/cosx sinx|; б) |4/0/0;2/5/0; 3/1/9|; в) |1/4/7; 2/5/8; 3/6/9|

In [12]:
# а)

x = math.pi / 4

A = np.array([[math.sin(x), -math.cos(x)], [math.cos(x), math.sin(x)]])

print(f'A:\n{A}\n')

print(f'Trial(det(A)): {matrix_determinant_2x2_3x3(A)}\n')

print(f'Check(det(A)): {np.linalg.det(A)}\n')

A:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

Trial(det(A)): 1.0000000000000002

Check(det(A)): 1.0



In [13]:
# б)

A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])

print(f'A:\n{A}\n')

print(f'Trial(det(A)): {matrix_determinant_2x2_3x3(A)}\n')

print(f'Check(det(A)): {np.linalg.det(A)}\n')

A:
[[4 2 3]
 [0 5 1]
 [0 0 9]]

Trial(det(A)): 180

Check(det(A)): 180.0



In [14]:
# в)

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f'A:\n{A}\n')

print(f'Trial(det(A)): {matrix_determinant_2x2_3x3(A)}\n')

print(f'Check(det(A)): {np.linalg.det(A)}\n')

A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Trial(det(A)): 0

Check(det(A)): -9.51619735392994e-16



2. Определитель матрицы A равен 4. Найти:
а) det(A2);
б) det(AT);
в) det(2A).


Вариант а:
det(A2)=det(AA)=det(A)∗det(a)=4∗4=16
Вариант б:
det(AT)=det(A)=4
Вариант в:
det(2A)=det(A)∗2n=4∗2n, n - кол-во строк в матрице


In [15]:
A = np.array([[1, -2], [1, 2]])

print(f'A:\n{A}\n')
print(f'det(A): {np.linalg.det(A)}\n')

A:
[[ 1 -2]
 [ 1  2]]

det(A): 4.0



In [16]:
print(f'A:\n{A}\n')
print(f'det(A): {np.linalg.det(A)}\n')
print(f'A^2:\n{np.dot(A, A)}\n')
print(f'det(A^2): {np.linalg.det(np.dot(A, A))}\n')

A:
[[ 1 -2]
 [ 1  2]]

det(A): 4.0

A^2:
[[-1 -6]
 [ 3  2]]

det(A^2): 16.000000000000007



In [17]:
print(f'A:\n{A}\n')
print(f'det(A): {np.linalg.det(A)}\n')
print(f'A:\n{A.T}\n')
print(f'det(A.T): {np.linalg.det(A.T)}\n')

A:
[[ 1 -2]
 [ 1  2]]

det(A): 4.0

A:
[[ 1  1]
 [-2  2]]

det(A.T): 4.0



In [18]:
print(f'A:\n{A}\n')
print(f'det(A): {np.linalg.det(A)}\n')
print(f'2A:\n{np.dot(2, A)}\n')
print(f'det(2A): {2**(A.shape[0] + 2)}\n')
print(f'det(2A): {np.linalg.det(2 * A)}\n')

A:
[[ 1 -2]
 [ 1  2]]

det(A): 4.0

2A:
[[ 2 -4]
 [ 2  4]]

det(2A): 16

det(2A): 15.999999999999998



3. Доказать, что матрица (-2/4/-3;7/-14/7; -3/6/13) вырожденная

1) Если det(A)=0, то матрица A вырождена.
2) Если, как минимум, две строки матрицы A линейно зависимы, то матрица A вырождена.


In [19]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])

print(f'A:\n{A}\n')

A:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]



In [20]:
# 1)

print(f'A:\n{A}\n')
print(f'det(A): {np.linalg.det( A)}\n')

A:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]

det(A): 0.0



In [21]:
# 2)

print(f'A:\n{A}\n')
print(f'Умножим первую строку матрицы A на -2:')
print(f'-2{A[0]} = {A[1]}\n')
print(f'В результате умножения получаем вторую строку матрицы A:')
print(f'{-2 * A[0]} = {A[1]}')
print(f'Вторая строка матрицы A является линейной комбинацией первой строки матрицы A.')
print(f'Первая и вторая строки матрицы A линейнозависимы.')

A:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]

Умножим первую строку матрицы A на -2:
-2[-2  7 -3] = [  4 -14   6]

В результате умножения получаем вторую строку матрицы A:
[  4 -14   6] = [  4 -14   6]
Вторая строка матрицы A является линейной комбинацией первой строки матрицы A.
Первая и вторая строки матрицы A линейнозависимы.


4. Найти ранг матрицы:
а) (1/1/2;2/1/3;3/1/4)
б) (0/0/0/2;0/0/0/3;2/2/4/5;1/2/3/6)
 
Определение
Строчным рангом матрицы называется максимальное число линейно независимых строк этой матрицы.
Столбцовым рангом матрицы называется максимальное число линейно независимых столбцов этой матрицы.
Теорема
Строчный ранг матрицы всегда совпадает с столбцовым и равен максимальному размеру ее невырожденного минора.


In [22]:
# а)

A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])

print(f'A:\n{A}\n')

A:
[[1 2 3]
 [1 1 1]
 [2 3 4]]



In [23]:
print(f'A:\n{A}\n')
print(f'Сложим первую и вторую строки матрицы A:')
print(f'{A[0]} + {A[1]} = {A[0] + A[1]}\n')
print(f'В результате сложения получаем третью строку матрицы A:')
print(f'{A[2]}\n')
print(f'Третья строка матрицы A является линейной комбинацией первой и второй строк матрицы A.')
print(f'rank(A): 2\n')

A:
[[1 2 3]
 [1 1 1]
 [2 3 4]]

Сложим первую и вторую строки матрицы A:
[1 2 3] + [1 1 1] = [2 3 4]

В результате сложения получаем третью строку матрицы A:
[2 3 4]

Третья строка матрицы A является линейной комбинацией первой и второй строк матрицы A.
rank(A): 2



In [24]:
print(f'A:\n{A}\n')
print(f'rank(A): {np.linalg.matrix_rank(A)}\n')

A:
[[1 2 3]
 [1 1 1]
 [2 3 4]]

rank(A): 2



In [25]:
# б)

A = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])

print(f'A:\n{A}\n')

A:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]



In [26]:
print(f'A:\n{A}\n')
print(f'Вычтем из третьей строки вторую строку A:')
print(f'{A[2]} - {A[1]} = {A[2] - A[1]}\n')
print(f'В результате вычитания получаем первую строку матрицы A:')
print(f'{A[0]}\n')
print(f'Первая строка матрицы A является линейной комбинацией втрой и третьей строк матрицы A.')
print(f'rank(A): 3\n')

A:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]

Вычтем из третьей строки вторую строку A:
[0 0 4 3] - [0 0 2 2] = [0 0 2 1]

В результате вычитания получаем первую строку матрицы A:
[0 0 2 1]

Первая строка матрицы A является линейной комбинацией втрой и третьей строк матрицы A.
rank(A): 3



In [27]:
print(f'A:\n{A}\n')
print(f'rank(A): {np.linalg.matrix_rank(A)}\n')

A:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]

rank(A): 3

